# 📐 Day 03a: NumPy Linear Algebra — From Scratch to np.linalg

---

## 🎯 What You'll Master Today
- Matrix operations: dot, @, inv, det, solve
- Eigenvalues and eigenvectors
- SVD decomposition
- PCA implementation using NumPy only

**Goal:** Implement PCA from pure NumPy in an interview.

---

```
╔═══════════════════════════════════════════════════════════════════╗
║  np.linalg — ESSENTIAL FUNCTIONS                                 ║
╠═══════════════════════════════════════════════════════════════════╣
║                                                                   ║
║  np.dot(A, B) or A @ B    → matrix multiplication              ║
║  np.linalg.inv(A)         → inverse matrix                     ║
║  np.linalg.det(A)         → determinant                        ║
║  np.linalg.solve(A, b)    → solve Ax = b                      ║
║  np.linalg.eig(A)         → eigenvalues, eigenvectors         ║
║  np.linalg.svd(A)         → U, S, Vt decomposition            ║
║  np.linalg.norm(x)        → vector/matrix norm                ║
║  A.T                      → transpose                          ║
║                                                                   ║
╚═══════════════════════════════════════════════════════════════════╝
```

---

In [1]:
import numpy as np

# ============================================================
# Matrix Operations
# ============================================================

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiply (3 equivalent ways)
print(f"A @ B = \n{A @ B}")
print(f"np.dot(A, B) = \n{np.dot(A, B)}")
print(f"np.matmul(A, B) = \n{np.matmul(A, B)}")

# Transpose
print(f"\nA.T = \n{A.T}")

# Inverse
A_inv = np.linalg.inv(A)
print(f"\nA_inv = \n{A_inv}")
print(f"A @ A_inv ≈ I: \n{np.round(A @ A_inv, 10)}")

# Determinant
print(f"\ndet(A) = {np.linalg.det(A):.1f}")  # -2.0

# Norm
v = np.array([3, 4])
print(f"\nnorm([3,4]) = {np.linalg.norm(v)}")  # 5.0

A @ B = 
[[19 22]
 [43 50]]
np.dot(A, B) = 
[[19 22]
 [43 50]]
np.matmul(A, B) = 
[[19 22]
 [43 50]]

A.T = 
[[1 3]
 [2 4]]

A_inv = 
[[-2.   1. ]
 [ 1.5 -0.5]]
A @ A_inv ≈ I: 
[[1. 0.]
 [0. 1.]]

det(A) = -2.0

norm([3,4]) = 5.0


In [ ]:
# ============================================================
# Solving Linear Systems: Ax = b
# ============================================================

# Problem: 2x + 3y = 8, x + 4y = 9
A = np.array([[2, 3], [1, 4]])
b = np.array([8, 9])

# Method 1: np.linalg.solve (preferred — faster, more stable)
x = np.linalg.solve(A, b)
print(f"solve: x={x[0]:.2f}, y={x[1]:.2f}")

# Method 2: Using inverse (less stable, slower)
x2 = np.linalg.inv(A) @ b
print(f"inv:   x={x2[0]:.2f}, y={x2[1]:.2f}")

# Verify
print(f"Check: A @ x = {A @ x}")
print(f"Expected: b = {b}")

print("\n💡 Always use solve() over inv() — more numerically stable!")

solve: x=1.00, y=2.00
inv:   x=1.00, y=2.00
Check: A @ x = [8. 9.]
Expected: b = [8 9]

💡 Always use solve() over inv() — more numerically stable!


: 

In [ ]:
# ============================================================
# Eigenvalues & Eigenvectors
# ============================================================

# A * v = λ * v
# v = eigenvector (direction that doesn't change)
# λ = eigenvalue (how much it stretches)

A = np.array([[4, 2], [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors (columns): \n{eigenvectors}")

# Verify: A @ v = λ * v
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lam = eigenvalues[i]
    lhs = A @ v
    rhs = lam * v
    print(f"\nλ={lam:.2f}: A@v = {np.round(lhs, 4)}, λ*v = {np.round(rhs, 4)} ✅")

print("\n💡 Eigenvectors of covariance matrix → principal components (PCA)!")

In [ ]:
# ============================================================
# SVD — Singular Value Decomposition
# ============================================================

# A = U @ S @ Vt
# U: left singular vectors (m×m)
# S: singular values (diagonal, sorted descending)
# Vt: right singular vectors (n×n)

A = np.array([[1, 2, 3], [4, 5, 6]])

U, s, Vt = np.linalg.svd(A, full_matrices=False)
print(f"U shape:  {U.shape}")
print(f"s (singular values): {s}")
print(f"Vt shape: {Vt.shape}")

# Reconstruct
S = np.diag(s)
reconstructed = U @ S @ Vt
print(f"\nReconstruct check: \n{np.round(reconstructed, 10)}")
print(f"Original: \n{A}")

# Low-rank approximation (keep top-k singular values)
k = 1
approx = U[:, :k] @ S[:k, :k] @ Vt[:k, :]
print(f"\nRank-{k} approximation: \n{np.round(approx, 2)}")

print("\n💡 SVD use cases: dimensionality reduction, recommender systems, image compression")

In [ ]:
# ============================================================
# ⭐ PCA From Scratch — Using Only NumPy
# ============================================================

# This is the interview classic!

def pca_numpy(X, n_components):
    """
    PCA implementation using NumPy only.
    X: (n_samples, n_features)
    Returns: (n_samples, n_components)
    """
    # Step 1: Center the data (subtract mean)
    mean = X.mean(axis=0)
    X_centered = X - mean
    
    # Step 2: Compute covariance matrix
    cov = (X_centered.T @ X_centered) / (X_centered.shape[0] - 1)
    # Equivalent: np.cov(X_centered.T)
    
    # Step 3: Eigendecomposition
    eigenvalues, eigenvectors = np.linalg.eigh(cov)  # eigh for symmetric
    
    # Step 4: Sort by eigenvalue (descending)
    idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[idx]
    eigenvectors = eigenvectors[:, idx]
    
    # Step 5: Select top-k components
    components = eigenvectors[:, :n_components]
    
    # Step 6: Project data
    X_projected = X_centered @ components
    
    # Explained variance ratio
    explained_var = eigenvalues[:n_components] / eigenvalues.sum()
    
    return X_projected, explained_var

# Test with synthetic data
np.random.seed(42)
X = np.random.randn(100, 5)  # 100 samples, 5 features
# Add correlation
X[:, 2] = X[:, 0] * 2 + np.random.randn(100) * 0.1
X[:, 3] = X[:, 1] * -1.5 + np.random.randn(100) * 0.1

X_pca, var_explained = pca_numpy(X, n_components=2)

print(f"Original shape:  {X.shape}")
print(f"PCA shape:       {X_pca.shape}")
print(f"Variance explained: {var_explained}")
print(f"Total explained:    {var_explained.sum():.2%}")

In [ ]:
# ============================================================
# PCA using SVD (alternative — often more numerically stable)
# ============================================================

def pca_svd(X, n_components):
    """PCA via SVD — no explicit covariance matrix."""
    X_centered = X - X.mean(axis=0)
    U, s, Vt = np.linalg.svd(X_centered, full_matrices=False)
    
    # Project: X_centered @ V[:, :k] = U[:, :k] * s[:k]
    X_projected = U[:, :n_components] * s[:n_components]
    
    # Explained variance
    explained_var = (s[:n_components] ** 2) / (s ** 2).sum()
    
    return X_projected, explained_var

X_pca2, var2 = pca_svd(X, 2)
print(f"SVD PCA shape: {X_pca2.shape}")
print(f"Variance explained: {var2}")
print(f"\n💡 SVD avoids computing covariance matrix → better for high-dimensional data")

print("\nPCA steps from memory:")
print("  1. Center data (subtract mean)")
print("  2. Covariance matrix (X.T @ X / n-1) OR SVD")
print("  3. Eigendecomposition (eigh for symmetric)")
print("  4. Sort eigenvalues descending")
print("  5. Select top-k eigenvectors")
print("  6. Project: X_centered @ components")

---

## 🗺️ Linear Algebra Pattern Map

```
╔═══════════════════════════════════════════════════════════════════╗
║  np.linalg CHEAT SHEET                                           ║
╠═══════════════════════════════════════════════════════════════════╣
║                                                                   ║
║  MULTIPLY:  A @ B  (matrix)   A * B  (element-wise)            ║
║  SOLVE:     np.linalg.solve(A, b)   NOT  inv(A) @ b            ║
║  EIGEN:     eig(A) → general,  eigh(A) → symmetric (faster)   ║
║  SVD:       U, s, Vt = svd(A)  → A ≈ U @ diag(s) @ Vt        ║
║  NORM:      norm(v)  norm(A, 'fro')  norm(A, 2)               ║
║                                                                   ║
║  PCA RECIPE:                                                     ║
║    1. Center (X - mean)                                         ║
║    2. Cov matrix or SVD                                         ║
║    3. Top-k eigenvectors                                        ║
║    4. Project: X_centered @ components                          ║
║                                                                   ║
╚═══════════════════════════════════════════════════════════════════╝
```

---

## 📝 Interview Questions

| # | Question | Key Points |
|---|----------|-----------|
| 1 | Implement PCA from scratch? | Center → cov → eigh → sort → top-k → project |
| 2 | eig vs eigh? | eigh for symmetric/Hermitian (faster, real eigenvalues). Covariance is symmetric → eigh |
| 3 | solve vs inv? | solve is faster and more numerically stable. Never use inv for solving Ax=b |
| 4 | What is SVD? | A = U S Vt. Used in PCA, recommender systems, image compression |
| 5 | PCA via cov vs SVD? | SVD avoids explicit cov matrix, better for high-dimensional data |

---

## ┌──────────────────────────────────────────────────────────┐
## │              📌 KEY TAKEAWAYS                            │
## ├──────────────────────────────────────────────────────────┤
## │                                                          │
## │  • @ for matrix multiply, solve() for Ax=b              │
## │  • eigh() for symmetric matrices (covariance)           │
## │  • PCA = center → cov → eigen → top-k → project       │
## │  • SVD is alternate PCA path (more stable)              │
## │  • Memorize the 6-step PCA recipe                       │
## │                                                          │
## └──────────────────────────────────────────────────────────┘

---

## ⏭️ Next Up: **NumPy Tricks** — einsum, where, vectorize